
# cargo-vet audits file

[audits]

[[trusted.bellman]]
criteria = "safe-to-deploy"
user-id = 6289 # Jack Grigg (str4d)
start = "2021-06-04"
end = "2027-09-25"

[[trusted.bls12_381]]
criteria = "safe-to-deploy"
user-id = 6289 # Jack Grigg (str4d)
start = "2021-06-03"
end = "2027-09-25"

[[trusted.ff]]
criteria = "safe-to-deploy"
user-id = 1244 # Sean Bowe (ebfull)
start = "2019-10-08"
end = "2027-09-25"

[[trusted.ff_derive]]
criteria = "safe-to-deploy"
user-id = 1244 # Sean Bowe (ebfull)
start = "2019-10-08"
end = "2027-09-25"

[[trusted.group]]
criteria = "safe-to-deploy"
user-id = 1244 # Sean Bowe (ebfull)
start = "2019-10-08"
end = "2027-09-25"

[[trusted.jubjub]]
criteria = "safe-to-deploy"
user-id = 6289 # Jack Grigg (str4d)
start = "2021-06-03"
end = "2027-09-25"

[[trusted.pairing]]
criteria = "safe-to-deploy"
user-id = 6289 # Jack Grigg (str4d)
start = "2022-12-06"
end = "2027-09-25"

[[trusted.pasta_curves]]
criteria = "safe-to-deploy"
user-id = 6289 # Jack Grigg (str4d)
start = "2021-03-03"
end = "2027-09-25"

[[trusted.reddsa]]
criteria = "safe-to-deploy"
user-id = 159631 # Conrado (conradoplg)
start = "2023-03-09"
end = "2027-09-25"

[[trusted.redjubjub]]
criteria = "safe-to-deploy"
user-id = 159631 # Conrado (conradoplg)
start = "2025-02-18"
end = "2027-09-25"

[[trusted.sapling-crypto]]
criteria = "safe-to-deploy"
user-id = 169181 # Kris Nuttycombe (nuttycom)
start = "2024-08-12"
end = "2027-09-25"

[[trusted.zcash_note_encryption]]
criteria = "safe-to-deploy"
user-id = 169181 # Kris Nuttycombe (nuttycom)
start = "2023-03-22"
end = "2027-09-25"

[[trusted.zip32]]
criteria = "safe-to-deploy"
user-id = 6289 # Jack Grigg (str4d)
start = "2023-12-06"
end = "2027-09-25"
